### ISSUE TITLE
gnuradio-redhawk error. The error with gr-component_converter execute.

### ISSUE THREAD

**Issue by polcoolov** [Geontech/gnuradio-redhawk#2]
I tried to deploy a GNURadio Flow Graph as a Component with GNURadio-REDHAWK Integration (https://github.com/GeonTech/gnuradio-redhawk). I selected Traditional Integration way (https://github.com/Geontech/gnuradio-redhawk/tree/master/1-traditional) and used _gr-redhawk_integration_python_ and _gr-component_converter packages_.

An error occurred during the Component Generation and don't generated the component.

My system and tools versions: CentOS Linux 7, Python 2.7.5, REDHAWK 2.2.1, GNU Radio 3.7.9. Details in [system_tools_versions.TXT](https://github.com/Geontech/gnuradio-redhawk/files/3043320/system_tools_versions.TXT).
After installing the GNU Radio has installed packages: _gr-redhawk_integration_python_, _gr-component_converter_.
Created and configured the Flow Graph to meet requirements with _redhawk_source_ and _redhawk_sink_ blocks.

An error occurred during the Component Generation, which is indicated in the 
[error_redhawk_codegen.TXT](https://github.com/Geontech/gnuradio-redhawk/files/3043327/error_redhawk_codegen.TXT).

Maybe the reason for the error in the difference of REDHAWK versions (need 2.0.6, but my version is 2.2.1)?
May I ask how to solve this problem?

**Comment by btgoodwin** [comment]
That's correct.  The submodules referenced in this top-level project were developed against an older version of REDHAWK ([reference](https://github.com/Geontech/gr-redhawk_integration_python#requirements)).

There is a new, C++ variation of this integration pattern that has been pushed recently, however this top-level build repository hasn't been updated yet (see for example, the new [gr-redhawk_integration](https://github.com/GeonTech/gr-redhawk_integration) repository).  There are also updates to the component converter which have been pushed to that repository.  FWIW, the latest version also supports a newer release of GNURadio based off the pybombs installation.

We do plan on updating this repository soon to collect these changes.

**Comment by polcoolov** [comment]
Thank you! I will wait on updating new gr-redhawk_integration repository.

**Comment by btgoodwin** [comment]
I apologize; I misunderstood the status of this one.  It was pushed internally; they have not pushed it externally (yet).  That's coming soon.

**Comment by btgoodwin** [comment]
FYI the `develop` branch of this repository has been pushed to point at the 2.2.1 versions of code, however the docker-based approach is giving us a little frustration (hence we haven't merged to master yet).  The non-docker version that you were approaching has been pushed to the master branches of the individual repositories (the integration package OOT module, component converter, etc.).  In all cases, we have not performed extensive performance testing, but we are expecting this new package to outperform the old Python-based approach by a wide margin.

Thank you for your patience.  Please let us know if you run into any more friction.

**Comment by polcoolov** [comment]
I deployed a GNURadio Flow Graph as a Component with _develop_ branch of this repository (https://github.com/Geontech/gnuradio-redhawk/tree/develop) on Redhawk 2.2.1 version. The generation and installation of the component was successful with GNU Radio 3.7.11. The component is successfully running as part of waveform. Thank you, your recommendations were very helpful!

**Comment by btgoodwin** [comment]
Excellent! Thank you for the update.
